apiVersion: v1
kind: Secret
metadata:
  name: dagshub-mlflow
  namespace: fraud-staging
type: Opaque
stringData:
  tracking_uri: "https://dagshub.com/<USER>/<REPO>.mlflow"
  username: "<USER>"
  token: "<DAGSHUB_TOKEN>"
---
apiVersion: v1
kind: Secret
metadata:
  name: dagshub-mlflow
  namespace: fraud-prod
type: Opaque
stringData:
  tracking_uri: "https://dagshub.com/<USER>/<REPO>.mlflow"
  username: "<USER>"
  token: "<DAGSHUB_TOKEN>"
