apiVersion: v1
kind: Secret
metadata:
  name: dagshub-mlflow
type: Opaque
stringData:
  tracking_uri: "https://dagshub.com/krichenyoussef/MLops.mlflow"
  username: "krichenyoussef"
  token: "9e7ef4a8033da85761edf8f51ce132432594d3b7"
